// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserId int64 `json:"userid"`
}

type UserInfoResp struct {
	UserId   int64  `json:"userid"`
	NickName string `json:"nickname"`
	Mobile   string `json:"mobile"`
}

type UserUpdateResp struct {
	UserId   int64  `json:"userid"`
	NickName string `json:"nickname"`
}

type UserUpdateReq struct {
	Flag bool `json:"flag"`
}

type UserCreateReq struct {
	Mobile   string `json:"mobile"`
	NickName string `json:"nickname"`
}

type UserCreateResp struct {
	Flag bool `json:"flag"`
}

type UserTestReq struct {
}

type UserTestResp struct {
}
